### PR TITLE
Some initial example tests

### PR DESCRIPTION
**Pull request by kanishka-azimi**

### CODE REVIEW

**Comment by hvr** [comment]
@kanishka-azimi you may want to remove the ` - TEST="--disable-tests"` line from the .travis.yml file

**Comment by kanishka-azimi** [comment]
Okay, will do.

Thanks for issue response as well. I defaulted to the same conclusion, but more out of expediency.

**Comment by kanishka-azimi** [comment]
I skimmed parts of Cabal library and cabal-install to have a better guess of typical values for CompInfo, UnitId. I gathered that UnitId is Package Id + ABI Hash. I am unclear if Exe Dependencies refers to various tools one might reference for building, or if it refers to executables produced by packages a given package depends on. I was also unclear why legacy version of Cabal need multiple components. My best guess is that legacy versions have only one unit, and all components listed under that unit, which is somehow related to dependencies being shared amongst all components.

I can switch to another style if you prefer. The parenthesis over dollar signs in the testCase is to generally avoid dollar signs per some people's advice.

**Comment by kanishka-azimi** [comment]
Feel free to reopen later. I am closing to minimize noise in this repo. I might revisit and add some more tests to this branch to represent various typical sections and dependencies.

**Pull request closed without merging**
